WIP : Add Stories request
livdroid/hackernews_flutter pull request #2
Opened 2020-01-02 11:02 UTC by livdroid

2020-01-02 20:15 UTC, ccreusot commented on lib/blocs/new_and_top_stories_bloc.dart
> +import '../entity/story.dart';
Attention ton import, essaye d'avoir `package:flutter_hcknews/entity/story.dart`

2020-01-02 20:15 UTC, ccreusot commented on lib/entity/story.dart
> +  String get by => _by;
ok, je penses que tu peux retirer les get/set et remettre en publique tes propriétées. Ça ressemble trop a Java sinon, et ce n'est pas nécessaire :)

2020-01-02 20:15 UTC, ccreusot commented on lib/repositories/stories_repository_impl.dart
> +import '../entity/story.dart';
Même chose qu'au dessus attention au import ;-)

2020-01-02 20:15 UTC, ccreusot commented on lib/usecases/new_and_top_stories_use_case.dart
> +import '../entity/story.dart';
Même chose pour l'import

2020-01-02 20:15 UTC, ccreusot commented on test/new_and_top_stories_bloc_test.dart
> +import '../lib/entity/story.dart';
Import ! :-D

2020-01-02 20:15 UTC, ccreusot commented on test/hackernews_service_test.dart
> +void main() {
Attention içi tu test principalement JsonDecode, ce n'est pas nécessaire. Tu devrais plus tester HackerNewsServiceImpl.

2020-01-02 20:15 UTC, ccreusot commented on lib/repositories/stories_repository_impl.dart
> +      final listId = List<int>.from(json.decode(response.body).map((x) => x));
utilise `jsonDecode` plutôt que l'objet json.

2020-01-02 20:15 UTC, ccreusot commented on lib/repositories/stories_repository_impl.dart
> +      final listId = List<int>.from(json.decode(response.body).map((x) => x));
Alors içi tu dois pouvoir utiliser compute.
cf : https://flutter.dev/docs/cookbook/networking/background-parsing

2020-01-03 17:37 UTC, livdroid commented on lib/blocs/new_and_top_stories_bloc.dart
> +import '../entity/story.dart';
Bien vu c'est ça qui me causait l'erreur que je t'avais envoyé en capture :)

2020-01-05 10:14 UTC, ccreusot commented on lib/repositories/stories_repository_impl.dart
> +      return compute(parseStoryList, response.body);
👍

2020-01-05 10:14 UTC, ccreusot commented on lib/repositories/stories_repository_impl.dart
>  class StoriesRepositoryImpl implements StoriesRepository {
Il manque le unit test du repo ;-)

2020-01-12 09:42 UTC, ccreusot requested changes

2020-01-12 09:42 UTC, ccreusot commented on test/stories_repository_test.dart
> +}
Tu test ton répository içi pas besoin de le Mock ;-)

2020-01-12 09:44 UTC, ccreusot commented on test/stories_repository_test.dart
> +}
Garde ton mock de ton service et c'est l'appelle du service qui doit être mock :
`when(hackerNewsService.fetchNewsAndTopStories().thenAnswer(...)`

2020-01-12 09:45 UTC, ccreusot commented on test/stories_repository_test.dart
> +}
Pour que le test soit valable tu vérifié que ton repo ton service :)

2020-01-16 09:56 UTC, ccreusot approved these changes

2020-01-16 09:56 UTC, merged