Open story + tests
livdroid/hackernews_flutter pull request #7
Opened 2020-02-01 21:46 UTC by livdroid

2020-02-02 07:49 UTC, ccreusot commented on lib/blocs/new_and_top_stories_bloc.dart
> +
Je ne le vois pas utiliser dans la vue.

2020-02-02 07:49 UTC, ccreusot commented on test/bloc/new_and_top_stories_bloc_test.dart
> +   */
Ah ? petit problème pour pouvoir tester ? :)

2020-02-02 07:49 UTC, ccreusot commented on test/bloc/new_and_top_stories_bloc_test.dart
> +   */
Ok, pour réaliser tes test il faudrait une interface qui définisse par exemple Share et une autre URLLauncher dont leurs implem serait les lib que tu as utilisé. Du coup tu seras obliger de les passer dans le constructeur de l'objet Bloc pour comme pour le UseCase ;-)

2020-02-08 10:38 UTC, ccreusot requested changes

2020-02-08 10:38 UTC, ccreusot commented on test/bloc/new_and_top_stories_bloc_test.dart
> +}
Good mais tu testes quand tout va bien, il te manque les cas d'erreur, qui peuvent juste s'assurer que tu ne fasse rien dans le Bloc en cas d'erreur :)

2020-02-13 13:00 UTC, livdroid commented on test/bloc/new_and_top_stories_bloc_test.dart
> +}
Cas d'erreur ajouté, je ferai la gestion de l'erreur côté UI sur une autre PR :)

2020-02-13 13:25 UTC, ccreusot approved these changes

2020-02-13 13:25 UTC, merged